---

- name: Configure servers with ruby support for single user
  hosts: all
  user: 'vagrant'
  vars:
    rvm1_rubies: ['ruby-2.3.1', 'ruby-2.3.0']
    rvm1_user: 'vagrant'

  roles:
    - rvm_io.ruby
    - common
