---

- name: Configure servers with ruby support for single user
  hosts: setup
  user: 'vagrant'
  vars:
    rvm1_rubies: ['ruby-2.3.1']
    rvm1_user: 'vagrant'
  roles:
    - rvm_io.ruby
    - common
  tags:
    - init-setup

- name: Setup Staging & Production Servers
  hosts: servers
  user: 'vagrant'
  sudo: yes
  vars:
    rvm1_rubies: ['ruby-2.3.1']
    rvm1_user: 'deploy'
  roles:
    - abtris.nginx-passenger
    - ANXS.postgresql
    - rvm_io.ruby
  tags:
    - servers
