# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://manski.net/2016/09/vagrant-multi-machine-tutorial/
# Original bento box didn't work - Switched to trusty64
BOX_IMAGE = "ubuntu/trusty64"
NODE_COUNT = 3
MACHINES = ['master','node1', 'node2', 'node3']
IP_ADDRESS_START = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.define "#{MACHINES[0]}" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "#{MACHINES[0]}"
    subconfig.vm.network :private_network, ip: "#{IP_ADDRESS_START}"
    config.vm.synced_folder "./jobs", "/home/vagrant/jobs", type: "nfs"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "#{MACHINES[i]}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE # change light weight box
      subconfig.vm.hostname = "#{MACHINES[i]}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 110}"
    end
  end

  # Install avahi on all machines & copy ssh key for quick logins
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      apt-get install -y avahi-daemon libnss-mdns
      echo "<==== Copying KEYS ====>"
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      # known hosts
    SHELL
  end

  config.vm.provision "docker" do |d|
    d.pull_images "jrottenberg/ffmpeg"
  end
end
