#!/usr/bin/env ruby

require_relative 'lib/master_control'


mc = RelationshipOfCommand::MasterControl.new
choice, input, output = ARGV[0], ARGV[1], ARGV[2]

puts `pwd`

case choice
when 'running_jobs'
  mc.running_jobs input, output
else
  puts 'Don\'t know that one'
  puts 'Try: '
  puts './mc running_jobs test.mpg, test.mov'
end
