# wordpress:
#   image: wordpress
#   links:
#     - wordpress_db:mysql
#   ports:
#     - 8080:80
# wordpress_db:
#   image: mysql
#   environment:
#     MYSQL_ROOT_PASSWORD: wordpress
# phpmyadmin:
#   image: corbinu/docker-phpmyadmin
#   links:
#     - wordpress_db:mysql
#   ports:
#     - 8181:80
#   environment:
#     MYSQL_USERNAME: root
#     MYSQL_ROOT_PASSWORD: wordpress
nginx:
  restart: always
  image: nginx
  ports:
    - 8080:80
  volumes:
    - ./X:/X
  restart: always
