# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://manski.net/2016/09/vagrant-multi-machine-tutorial/
# Original bento box didn't work - Switched to trusty64
BOX_IMAGE = "ubuntu/trusty64"
Vagrant.configure("2") do |config|

  config.vm.define "wordpress" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "wordpress"
    subconfig.vm.network :private_network, ip: "192.168.56.105"
    config.vm.synced_folder "~/Projects/vagrant/MultiMachines/Projects", "/home/vagrant/Projects", type: "nfs"
  end

  # Install avahi on all machines & copy ssh key
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      apt-get install -y avahi-daemon libnss-mdns
      echo "<==== Copying KEYS ====>"
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      # known hosts
    SHELL
  end

  config.vm.provision "docker" do |d|
    d.pull_images "wordpress"
    d.pull_images "mysql"
    d.pull_images "phpmyadmin/phpmyadmin"
  end
end
