---
- name: update and upgrade apt packages
  sudo: yes
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600

- name: Install packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
       - htop
       - vim
       - git
