---
- name: ffmpeg_build
  file: path=/home/vagrant/ffmpeg_build state=directory
- name: ffmpeg_sources
  file: path=/home/vagrant/ffmpeg_sources state=directory
- name: input
  file: path=/home/vagrant/input state=directory
  tags:
    - input
- name: output
  file: path=/home/vagrant/output state=directory
  tags:
    - output

# https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
- name: yasm
  script: ffmpeg/scripts/yasm.sh
  tags:
    - yasm

- name: x264
  script: ffmpeg/scripts/x264.sh
  tags:
    - x264

# may need to reboot
- name: x265
  script: ffmpeg/scripts/x265.sh
  tags:
    - x265

- name: libfdk-aac
  script: ffmpeg/scripts/libfdk-aac.sh
  tags:
    - libfdk-aac

- name: libmp3lame
  script: ffmpeg/scripts/libmp3lame.sh
  tags:
    - libmp3lame

- name: libopus
  script: ffmpeg/scripts/libopus.sh
  tags:
    - libopus

- name: libvpx
  script: ffmpeg/scripts/libvpx.sh
  tags:
    - libvpx

- name: ffmpeg
  script: ffmpeg/scripts/ffmpeg.sh
  tags:
    - ffmpeg
