source 'https://rubygems.org'

gem 'colorize'
gem 'net-scp'
gem 'net-ssh'
gem 'dotenv'
gem 'ruby-progressbar'
gem 'rspec'
gem 'sqlite3'

# Server Testing
# http://serverspec.org/
# gem 'serverspec'

# Thor CommandLineInterface
